PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE WORDS_I_KNOW (
ID INT PRIMARY KEY NOT NULL,
WORD TEXT NOT NULL);
INSERT INTO WORDS_I_KNOW VALUES(1,'HELLO');
INSERT INTO WORDS_I_KNOW VALUES(2,'GOODBYE');
INSERT INTO WORDS_I_KNOW VALUES(3,'Hannah');
INSERT INTO WORDS_I_KNOW VALUES(4,'Christian');
CREATE TABLE CURRENT_TRUE_WORD (
WORD TEXT NOT NULL);
INSERT INTO CURRENT_TRUE_WORD VALUES('HELLO');
INSERT INTO CURRENT_TRUE_WORD VALUES('HELLO');
INSERT INTO CURRENT_TRUE_WORD VALUES('Quality');
COMMIT;
